# app/agent/enrichment_assistant.py
from openai import OpenAI
from typing import Optional

class EnrichmentAssistant:
    def __init__(self, assistant_id: str, vector_store_id: Optional[str] = None):
        self.client = OpenAI()
        self.assistant_id = assistant_id
        self.vector_store_id = vector_store_id

    def enrich_response(self, user_message: str, draft_response: str) -> str:
        """
        Enriches the main agent's response using the OpenAI Assistant and its vector store.
        """
        # Combine the original message and the draft for context
        input_prompt = (
            f"The following is a draft response generated by the main agent.\n"
            f"User message: {user_message}\n\n"
            f"Draft response:\n{draft_response}\n\n"
            f"Your task: Improve, enrich, and make this response more complete and accurate "
            f"using your internal knowledge base and style guidelines. "
            f"Keep the answer in the same language as the draft."
        )

        # Create a thread for this enrichment cycle
        thread = self.client.beta.threads.create()

        # Send message to assistant
        self.client.beta.threads.messages.create(
            thread_id=thread.id,
            role="user",
            content=input_prompt,
        )

        # Run the assistant (uses storage vector store automatically)
        run = self.client.beta.threads.runs.create_and_poll(
            thread_id=thread.id,
            assistant_id=self.assistant_id
        )

        # Retrieve enriched response
        messages = self.client.beta.threads.messages.list(thread_id=thread.id)
        enriched_text = messages.data[0].content[0].text.value

        return enriched_text
