# app/agent/enrichment_assistant.py
import os
from openai import OpenAI
from typing import Optional

class EnrichmentAssistant:
    def __init__(self, assistant_id: str, vector_store_id: Optional[str] = None):
        # Variable custom de Railway, env estándar, o settings (.env vía pydantic,
        # que NO exporta a os.environ — sin este fallback fallaba en local).
        from retie_agent.config import settings
        api_key = (
            os.getenv("Openai_API_KEY")
            or os.getenv("OPENAI_API_KEY")
            or settings.OPENAI_API_KEY
        )
        if not api_key:
            raise RuntimeError("Missing OpenAI API key. Please set Openai_API_KEY or OPENAI_API_KEY.")
        
        # pass it explicitly to the OpenAI client
        self.client = OpenAI(api_key=api_key)
        self.assistant_id = assistant_id
        self.vector_store_id = vector_store_id

    def enrich_response(self, user_message: str, draft_response: str) -> str:
        input_prompt = (
            f"The following is a draft response generated by the main agent.\n"
            f"User message: {user_message}\n\n"
            f"Draft response:\n{draft_response}\n\n"
            f"Your task: Improve, enrich, and make this response more complete and accurate "
            f"using your internal knowledge base and style guidelines. "
            f"Keep the answer in the same language as the draft.\n"
            f"IMPORTANT: Return ONLY the improved response text, with no preamble, "
            f"no meta-comments (e.g. 'aquí tienes una versión mejorada') and no quotes around it — "
            f"your output goes directly to the end user."
        )

        thread = self.client.beta.threads.create()
        self.client.beta.threads.messages.create(thread_id=thread.id, role="user", content=input_prompt)
        self.client.beta.threads.runs.create_and_poll(thread_id=thread.id, assistant_id=self.assistant_id)
        messages = self.client.beta.threads.messages.list(thread_id=thread.id)
        return messages.data[0].content[0].text.value
